name: Fetch Yahoo Finance News

on:
  schedule:
    # 每6小时运行一次
    - cron: "0 */6 * * *"
  # 允许手动触发
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.7.0"
          cache: "npm"

      - name: Install dependencies
        run: cd backend && npm ci

      - name: Install required system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Check required secrets
        id: check_secrets
        run: |
          if [ -z "${{ secrets.NOTION_SECRET }}" ]; then
            echo "::warning::NOTION_SECRET is not set"
            echo "has_required_secrets=false" >> $GITHUB_OUTPUT
          elif [ -z "${{ secrets.NOTION_DATABASE_ID }}" ]; then
            echo "::warning::NOTION_DATABASE_ID is not set"
            echo "has_required_secrets=false" >> $GITHUB_OUTPUT
          elif [ -z "${{ secrets.AI_PROVIDER }}" ]; then
            echo "::warning::AI_PROVIDER is not set"
            echo "has_required_secrets=false" >> $GITHUB_OUTPUT
          else
            echo "has_required_secrets=true" >> $GITHUB_OUTPUT
          fi

      - name: Fetch Yahoo Finance News (Links Only)
        if: steps.check_secrets.outputs.has_required_secrets != 'true'
        run: |
          echo "Running in links-only mode due to missing required secrets"
          cd backend && node scripts/fetch-yahoo-news.js

      - name: Fetch Yahoo Finance News (Full Analysis)
        if: steps.check_secrets.outputs.has_required_secrets == 'true'
        run: cd backend && node scripts/fetch-yahoo-news.js
        env:
          # Notion配置
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

          # AI配置
          AI_PROVIDER: ${{ secrets.AI_PROVIDER }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          XAI_BASE_URL: ${{ secrets.XAI_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
